apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: unipro-site-ingress
  namespace: hofu-2025
  annotations:
    cert-manager.io/cluster-issuer: le-cf-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    ngins.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: hofu-2025.uniproject.jp
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: unipro-site
            port:
              number: 80
  tls:
  - hosts:
    - hofu-2025.uniproject.jp
    secretName: unipro-www-tls