---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-registry-secret
  namespace: hofu-2025
spec:
  encryptedData:
    .dockerconfigjson: AgBQ8oXSo0c95IYEabrKfdYPvuIRyIzYbPTj31j4b0YAZXIH2CEG9PPf0mQFbnpvGBaFUe57RR3rXBblVhiWVTBCL6YI4i21/zXTBIGlZGTpoCGXBXvtBmwyL+oeDTrpVOfJdfwgTksAstufJhaS/VomvVkKykVJb4dnVfphGKreyPmSeEeGAqhbiD68svaus4ceteXALgGRStu6Xrit8zMGFjpn6B5F286rrV65wBl+TvASKQmzwwnTYMgigMxXiWltvfcAjlnZoAuQrG2xcFt51HB7Ii2p9hZx6k1Ft3AN6ND2HwrCnn+aaNutvOqQcJUdQ1kpyKmJvFyXrKAwsUY+udi9/NP2MhGYV0fIVnVLY/HH/Zmr/lxnGz7ZQ4oZ36vurLL4eWfMVrXjnKPF9IckAusoy6sKsn9G0wu8epI1WHYsaBz0cVFAvGIGTWjSPiptSbs2jiDjZ2BCSIwXW+VV1+2kvFEtAAYWtks1A0mX03eIMKaxfdiDUN2zXP5uUz60aqFQJOtg5vFWb8zknSi+3XemDkOtFsvUHt+T1Db7DOH5cVPiGnyXzry5BnhcuqvSitnoHkNBqCSrs0PJ/foIF/BKZYbPP88JPChRzgq5p50D9yGpVNulzP2BJfn/QjZM62BCBapThWjp7Xhq8I1NyuGhUd8sJfateiv45TVPUlzHZBJ6CgOVlv/V8ieFwnqdIJHGqDrIBsaQVv4VFlYHek4OIt7O6uYV3Hx+0VzasYGzmK0eVQNhntiqJDi5xM/yUgXut8c5dLYmfIkfg4z6SdtzdCV17IIu2C9Da5lNyQQEIJ7Ec7GvBF44kvt/UkZMaxOkYgnmXVrixyNB8WAlACYnVV8yAO02uwnWJVgfU3fn+d4lnJoRFQS2E/IRe2qz+QYLRVsmSqSXf3cOrn94Pnwer2OIByUCgo+j1QwGlkPdUWY4Hs+G63J/toApdcAgpw==
  template:
    metadata:
      creationTimestamp: null
      name: harbor-registry-secret
      namespace: hofu-2025
    type: kubernetes.io/dockerconfigjson
